/// Flutter icons SodaIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SodaIcons
///      fonts:
///       - asset: fonts/SodaIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SodaIcons {
  SodaIcons._();

  static const _kFontFam = 'SodaIcons';
  static const String? _kFontPkg = null;

  static const IconData clock = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData broadcasts = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData broadcasts_outlined = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData broadcasts_1 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData broadcasts_2 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData broadcasts_outlined_1 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_outlined = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData listeners = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData listening = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData live = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin_outlined = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_outlined = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_outlined = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visibility = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visibility_off = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData article = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData article_outlined = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData broadcast = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_outlined = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
